name: 'Azure auth api call'
description: 'Make an http request to an authenticated API in azure '
inputs:
  tenant_id: 
    description: 'Azure AD Tenant ID'
    required: true
    default: '00000000-0000-0000-0000-000000000000'
  client_id: 
    description: 'App Registration Client ID'
    required: true
    default: '00000000-0000-0000-0000-000000000000'
  scope:
    description: 'OIDC Scope'
    required: true
    default: 'https://graph.microsoft.com/.default'
outputs:
  access_token:
    description: 'Microsoft Entra Id Access token for federated credentials'
runs:
  using: 'node16'
  main: 'dist/index.js'
